name : CI/CD

on:
    push:
        branches:
            - '*'
    pull_request:
        types: [ opened, synchronize, reopened ]

jobs:
    build:
        name: Build & Push
        runs-on: ubuntu-latest
        steps:
            - name: Clone repository
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Conventional commit check
              uses: cocogitto/cocogitto-action@v3
              with:
                  check-latest-tag-only: false
                  git-user: hoohoot
                  git-user-email: git@hoohoot.org

            - name: Login to Docker Repository
              uses: docker/login-action@v1
              with:
                  registry: rg.fr-par.scw.cloud/hoohoot-registry
                  username: nologin
                  password: ${{ secrets.SCALEWAY_TOKEN }}

            - name: Build
              id: docker_build
              if: github.ref != 'refs/heads/main'
              uses: docker/build-push-action@v2
              with:
                  context: ./
                  file: ./Dockerfile
                  push: false
                  tags: rg.fr-par.scw.cloud/hoohoot-registry/hoohoot-dashboard-frontend:latest

            - name: Build & Push
              id: docker_push
              if: github.event_name == 'push' && github.ref == 'refs/heads/main'
              uses: docker/build-push-action@v2
              with:
                  context: ./
                  file: ./Dockerfile
                  push: true
                  tags: rg.fr-par.scw.cloud/hoohoot-registry/hoohoot-dashboard-frontend:latest

            - name: Deploy
              uses: Consensys/kubernetes-action@master
              env:
                KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
              with:
                args: rollout restart deploy dashboard-frontend -n hoohoot